version: '3.0'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5444:5432
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/init-tables.sql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
